In [1]:
!pip install yfinance --upgrade --no-cache-dir
import yfinance as yf
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

Collecting yfinance
  Downloading yfinance-0.1.54.tar.gz (19 kB)
Requirement already satisfied, skipping upgrade: pandas>=0.24 in /home/haininhhoang94/anaconda3/envs/pyds/lib/python3.8/site-packages (from yfinance) (1.0.1)
Requirement already satisfied, skipping upgrade: numpy>=1.15 in /home/haininhhoang94/anaconda3/envs/pyds/lib/python3.8/site-packages (from yfinance) (1.18.1)
Collecting requests>=2.20
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 1.4 MB/s eta 0:00:01
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.9.tar.gz (8.1 kB)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /home/haininhhoang94/anaconda3/envs/pyds/lib/python3.8/site-packages (from pandas>=0.24->yfinance) (2019.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in /home/haininhhoang94/anaconda3/envs/pyds/lib/python3.8/site-packages (from pandas>=0.24->yfinance) (2.8.1)
Collecting idna<3,>=2.5
  Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 6.9 MB/s eta 0:00:011
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/haininhhoang94/anaconda3/envs/pyds/lib/python3.8/site-packages (from requests>=2.20->yfinance) (2019.11.28)
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 3.0 MB/s eta 0:00:01
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 11.1 MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: six>=1.5 in /home/haininhhoang94/anaconda3/envs/pyds/lib/python3.8/site-packages (from python-dateutil>=2.6.1->pandas>=0.24->yfinance) (1.14.0)
Building wheels for collected packages: yfinance, multitasking
  Building wheel for yfinance (setup.py) ... done
  Created wheel for yfinance: filename=yfinance-0.1.54-py2.py3-none-any.whl size=22409 sha256=dd5697307acb2c75087da8ae02bbde0025aad1b9ef9fc393ddc9c09b7eae3bf5
  Stored in directory: /tmp/pip-ephem-wheel-cache-duf92che/wheels/d9/55/e4/3fc43a4f56c7c18628bc24088be1d7168a832a91efa5ccc5da
  Building wheel for multitasking (setup.py) ... done
  Created wheel for multitasking: filename=multitasking-0.0.9-py3-none-any.whl size=8366 sha256=de2739d8865c0ca0dceed638e623c35b20dc658fddc8f34626e510e814857f57
  Stored in directory: /tmp/pip-ephem-wheel-cache-duf92che/wheels/57/6d/a3/a39b839cc75274d2acfb1c58bfead2f726c6577fe8c4723f13
Successfully built yfinance multitasking
Installing collected packages: idna, chardet, urllib3, requests, multitasking, yfinance
Successfully installed chardet-3.0.4 idna-2.9 multitasking-0.0.9 requests-2.23.0 urllib3-1.25.8 yfinance-0.1.54

## 1.Download 2 years of SPY, IVV, VOO and S&P500

In [2]:
tickers = ["^GSPC","SPY","IVV","VOO"]
ticker_benchmark = "^GSPC"
input_raw = yf.download(tickers, start='2018-01-01', end='2019-12-31', progress=False)

adj_close = input_raw["Adj Close"]
adj_close = adj_close.replace("", float("NaN"))
adj_close.dropna(inplace=True)
adj_close.head()

                   IVV         SPY         VOO        ^GSPC
Date
2018-01-02  259.769806  257.345001  236.406509  2695.810059
2018-01-03  261.275604  258.972717  237.812973  2713.060059
2018-01-04  262.407318  260.064240  238.855820  2723.989990
2018-01-05  264.066559  261.797302  240.386642  2743.149902
2018-01-08  264.651611  262.276093  240.884171  2747.709961

## 2.Compute the returns, active returns, and average active returns

In [3]:
# Function to calculate active return
def compute_active_return(target_return, benchmark_return):
    return target_return - benchmark_return

In [4]:
# Compute the returns
for ticker in tickers:
    adj_close[ticker + " Return"] = adj_close[ticker].diff()/adj_close[ticker].shift(1)

adj_close.dropna(inplace=True)
adj_close.head()

,IVV,SPY,VOO,^GSPC,^GSPC Return,SPY Return,IVV Return,VOO Return
Date,,,,,,,,
2018-01-03,261.275604,258.972717,237.812973,2713.060059,0.006399,0.006325,0.005797,0.005949
2018-01-04,262.407318,260.064240,238.855820,2723.989990,0.004029,0.004215,0.004331,0.004385
2018-01-05,264.066559,261.797302,240.386642,2743.149902,0.007034,0.006664,0.006323,0.006409
2018-01-08,264.651611,262.276093,240.884171,2747.709961,0.001662,0.001829,0.002216,0.002070
2018-01-09,265.255798,262.869720,241.391266,2751.290039,0.001303,0.002263,0.002283,0.002105

In [5]:
# Compute the active return
for ticker in tickers:
    adj_close[ticker + " Active Return"] = compute_active_return(adj_close[ticker + " Return"], adj_close[ticker_benchmark + " Return"])
adj_close.head()

,IVV,SPY,VOO,^GSPC,^GSPC Return,SPY Return,IVV Return,VOO Return,^GSPC Active Return,SPY Active Return,IVV Active Return,VOO Active Return
Date,,,,,,,,,,,,
2018-01-03,261.275604,258.972717,237.812973,2713.060059,0.006399,0.006325,0.005797,0.005949,0.0,-0.000074,-0.000602,-0.000449
2018-01-04,262.407318,260.064240,238.855820,2723.989990,0.004029,0.004215,0.004331,0.004385,0.0,0.000186,0.000303,0.000357
2018-01-05,264.066559,261.797302,240.386642,2743.149902,0.007034,0.006664,0.006323,0.006409,0.0,-0.000370,-0.000711,-0.000625
2018-01-08,264.651611,262.276093,240.884171,2747.709961,0.001662,0.001829,0.002216,0.002070,0.0,0.000167,0.000553,0.000407
2018-01-09,265.255798,262.869720,241.391266,2751.290039,0.001303,0.002263,0.002283,0.002105,0.0,0.000960,0.000980,0.000802

In [7]:
# Compute average active return
for ticker in tickers:
    if ticker == ticker_benchmark:
        continue
    avg_active_return = adj_close[ticker + " Active Return"].mean()
    print(f"{ticker} Average Active Return {avg_active_return}")

SPY Average Active Return 7.459497844043846e-05
IVV Average Active Return 7.66013294154672e-05
VOO Average Active Return 7.736530312260535e-05

## 3. Compute the tracking error and mean-adjusted tracking error

In [8]:
# Compute tracking error
for ticker in tickers:
    if ticker == ticker_benchmark:
        continue
    tracking_error = adj_close[ticker + " Active Return"].std()
    print(f"{ticker} tracking error {tracking_error}")

SPY tracking error 0.0004654583634601361
IVV tracking error 0.000422795592398827
VOO tracking error 0.0003906871866065818

In [9]:
for ticker in tickers:
    if ticker == ticker_benchmark:
        continue
    active_return_result = compute_active_return(adj_close[ticker + " Return"], adj_close[ticker_benchmark + " Return"])
    adj_tracking_error = np.sqrt(np.sum(active_return_result**2)/active_return_result.size)
    print(f"{ticker} Mean-adjusted tracking error {adj_tracking_error}")

SPY Mean-adjusted tracking error 0.0004709389141104054
IVV Mean-adjusted tracking error 0.0004292634132924043
VOO Mean-adjusted tracking error 0.0003978909452067465

## 4. According to above information, VOO tracks S&P500 better than the others. The reason is it has lowest value of Mean-adjusted Tracking Error even though it has highest Active Return but the value is not too different from other's active return value, as we know Mean-adjusted Tracking Error encompass the active return and the tracking record, VOO tend to tracks the S&P500 better and has more stable return flow.

## 5. Download these select SPDR funds over the same period as above ETFs

In [10]:
tickers = ["^GSPC", "XLB", "XLE", "XLF", "XLI", "XLK", "XLP", "XLRE", "XLU","XLV", "XLY"]
ticker_benchmark = "^GSPC"
input_raw = yf.download(tickers, start='2018-01-01', end='2019-12-31', progress=False)

adj_close = input_raw["Adj Close"]
adj_close = adj_close.replace("", float("NaN"))
adj_close.dropna(inplace=True)
adj_close.head()

,XLB,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY,^GSPC
Date,,,,,,,,,,,
2018-01-02,58.954708,66.782135,26.853806,73.183968,62.984173,53.430038,30.607880,48.911633,80.463112,97.627335,2695.810059
2018-01-03,59.367649,67.782272,26.998079,73.578140,63.509514,53.411137,30.617229,48.527386,81.233002,98.075562,2713.060059
2018-01-04,59.886227,68.191429,27.248152,74.116547,63.830574,53.562336,30.093857,48.124397,81.348473,98.397133,2723.989990
2018-01-05,60.366394,68.164146,27.325096,74.626099,64.501869,53.798588,30.159277,48.105663,82.041382,99.176659,2743.149902
2018-01-08,60.452820,68.573288,27.286625,74.933762,64.745079,53.930889,30.364889,48.555504,81.743050,99.293594,2747.709961

## 5. Compute the returns

In [11]:
for ticker in tickers:
    adj_close[ticker + " Return"] = adj_close[ticker].diff()/adj_close[ticker].shift(1)

adj_close.dropna(inplace=True)
adj_close.head()

,XLB,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY,...,XLB Return,XLE Return,XLF Return,XLI Return,XLK Return,XLP Return,XLRE Return,XLU Return,XLV Return,XLY Return
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-03,59.367649,67.782272,26.998079,73.578140,63.509514,53.411137,30.617229,48.527386,81.233002,98.075562,...,0.007004,0.014976,0.005373,0.005386,0.008341,-0.000354,0.000305,-0.007856,0.009568,0.004591
2018-01-04,59.886227,68.191429,27.248152,74.116547,63.830574,53.562336,30.093857,48.124397,81.348473,98.397133,...,0.008735,0.006036,0.009263,0.007317,0.005055,0.002831,-0.017094,-0.008304,0.001421,0.003279
2018-01-05,60.366394,68.164146,27.325096,74.626099,64.501869,53.798588,30.159277,48.105663,82.041382,99.176659,...,0.008018,-0.000400,0.002824,0.006875,0.010517,0.004411,0.002174,-0.000389,0.008518,0.007922
2018-01-08,60.452820,68.573288,27.286625,74.933762,64.745079,53.930889,30.364889,48.555504,81.743050,99.293594,...,0.001432,0.006002,-0.001408,0.004123,0.003771,0.002459,0.006818,0.009351,-0.003636,0.001179
2018-01-09,60.356789,68.400543,27.498222,75.414474,64.579697,53.855289,30.019089,48.077545,82.705414,99.488464,...,-0.001589,-0.002519,0.007755,0.006415,-0.002554,-0.001402,-0.011388,-0.009844,0.011773,0.001963

## 7. Internal function to compute active return and use that to compute mean-adjusted tracking error
### This function has been built in question 2 "def compute_active_return"

In [12]:
# compute mean-adjusted tracking error
tracking_params = pd.DataFrame(columns=tickers, index=["Avg. Active Return", "Tracking Error", "Mean-adjusted Tracking Error"])
for ticker in tickers:
    active_return_result = compute_active_return(adj_close[ticker + " Return"], adj_close[ticker_benchmark + " Return"])
    tracking_params.loc["Avg. Active Return", ticker] = active_return_result.mean()
    tracking_params.loc["Tracking Error", ticker] = active_return_result.std()
    tracking_params.loc["Mean-adjusted Tracking Error", ticker] = np.sqrt(np.sum(active_return_result**2)/active_return_result.size)

print("Average Active Return, Tracking Eror and Mean-adjusted Tracking Error of these ETFs")
tracking_params.drop(columns=[ticker_benchmark], inplace=True)
tracking_params.head()

Average Active Return, Tracking Eror and Mean-adjusted Tracking Error of these ETFs

,XLB,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY
Avg. Active Return,-0.000272154,-0.000538941,-7.19001e-05,-0.000124289,0.000429711,-4.12121e-05,9.48913e-05,0.000183938,0.000114918,0.000153818
Tracking Error,0.00608318,0.00902967,0.00570966,0.00491069,0.00538994,0.00732689,0.00940273,0.0109908,0.00498683,0.0041204
Mean-adjusted Tracking Error,0.0060832,0.00903674,0.00570441,0.00490736,0.00540168,0.00731969,0.00939382,0.0109813,0.00498318,0.00411916

## 8. According to above table, XLY is the most attractive ETFs. The reason is it has lowest value of Mean-adjusted Tracking Error and quite high Active Return, as we know Mean-adjusted Tracking Error encompass the active return and the tracking record, XLY tend to tracks the S&P500 better and has more stable return flow.