## Submission 3

### Compute the price return for each SPDR and the S&P 500 for each month of 2017

In [2]:
# In order for this module to work, please install the library xlrd by pip or conda!!!

import os
import pandas as pd
import numpy as np

file_name = "GWP_PTAP_Data_2010.10.08.xlsx"
file_dir = "./Data"
file = os.path.join(file_dir, file_name)
data_raw = pd.read_excel(file, sheet_name="10 SPDRs and S&P 500", header=1, index_col=0)
data_raw = data_raw.dropna()

data_raw

,XLE,XLB,XLI,XLY,XLP,XLV,XLF,XLK,XLU,XLRE,S&P 500
Date,,,,,,,,,,,
2016-12-30,75.320000,49.700001,62.220001,81.400002,51.709999,68.940002,23.250000,48.360001,48.570000,30.750000,2238.830078
2017-01-31,72.900002,51.959999,63.380001,84.830002,52.590000,70.519997,23.309999,50.080002,49.180000,30.709999,2278.870117
2017-02-28,71.379997,52.250000,65.860001,86.370003,55.099998,74.989998,24.540001,52.349998,51.770000,32.139999,2363.639893
2017-03-31,69.900002,52.410000,65.059998,87.949997,54.580002,74.360001,23.730000,53.310001,51.310001,31.600000,2362.719971
2017-04-28,67.839996,53.070000,66.339996,90.059998,55.180000,75.500000,23.530001,54.380001,51.700001,31.650000,2384.199951
2017-05-31,65.440002,53.080002,67.519997,91.050003,56.639999,76.080002,23.250000,56.529999,53.840000,31.860001,2411.800049
2017-06-30,64.919998,53.810001,68.110001,89.629997,54.939999,79.239998,24.670000,54.720001,51.959999,32.200001,2423.409912
2017-07-31,66.620003,54.639999,68.309998,91.360001,55.320000,79.889999,25.090000,57.160000,53.220001,32.590000,2470.300049
2017-08-31,62.970001,55.070000,68.459999,89.660004,54.709999,81.290001,24.700001,58.830002,54.970001,32.919998,2471.649902
2017-09-29,68.480003,56.799999,71.000000,90.080002,53.980000,81.730003,25.860001,59.099998,53.049999,32.240002,2519.360107
2017-10-31,67.910004,59.000000,71.529999,91.989998,53.090000,81.110001,26.600000,62.950001,55.119999,32.500000,2575.260010
2017-11-30,69.099998,59.560001,74.510002,96.650002,56.049999,83.470001,27.520000,63.840000,56.599998,33.450001,2647.580078
2017-12-29,72.260002,60.529999,75.669998,98.690002,56.889999,82.680000,27.910000,63.950001,52.680000,32.939999,2673.610107

In [4]:
# Loop for calculation
# For this problem, we will use normal return

tickers = data_raw.columns
price_return = pd.DataFrame()

for ticker in tickers:
    price_return[ticker] = data_raw[ticker].diff()/data_raw[ticker].shift(1)

price_return = price_return.dropna()
price_return

,XLE,XLB,XLI,XLY,XLP,XLV,XLF,XLK,XLU,XLRE,S&P 500
Date,,,,,,,,,,,
2017-01-31,-0.032130,0.045473,0.018644,0.042138,0.017018,0.022918,0.002581,0.035567,0.012559,-0.001301,0.017884
2017-02-28,-0.020851,0.005581,0.039129,0.018154,0.047728,0.063386,0.052767,0.045327,0.052664,0.046565,0.037198
2017-03-31,-0.020734,0.003062,-0.012147,0.018293,-0.009437,-0.008401,-0.033007,0.018338,-0.008885,-0.016801,-0.000389
2017-04-28,-0.029471,0.012593,0.019674,0.023991,0.010993,0.015331,-0.008428,0.020071,0.007601,0.001582,0.009091
2017-05-31,-0.035377,0.000188,0.017787,0.010993,0.026459,0.007682,-0.011900,0.039537,0.041393,0.006635,0.011576
2017-06-30,-0.007946,0.013753,0.008738,-0.015596,-0.030014,0.041535,0.061075,-0.032018,-0.034918,0.010672,0.004814
2017-07-31,0.026186,0.015425,0.002936,0.019302,0.006917,0.008203,0.017025,0.044591,0.024249,0.012112,0.019349
2017-08-31,-0.054788,0.007870,0.002196,-0.018608,-0.011027,0.017524,-0.015544,0.029216,0.032882,0.010126,0.000546
2017-09-29,0.087502,0.031415,0.037102,0.004684,-0.013343,0.005413,0.046964,0.004589,-0.034928,-0.020656,0.019303
2017-10-31,-0.008324,0.038732,0.007465,0.021203,-0.016488,-0.007586,0.028616,0.065144,0.039020,0.008064,0.022188
2017-11-30,0.017523,0.009492,0.041661,0.050658,0.055754,0.029096,0.034586,0.014138,0.026850,0.029231,0.028083
2017-12-29,0.045731,0.016286,0.015568,0.021107,0.014987,-0.009464,0.014172,0.001723,-0.069258,-0.015247,0.009832

### Compute the active return (relative to the S&P 500) for each SPDR for each month of 2017

In [6]:
ticker_benchmark = "S&P 500"
active_return = pd.DataFrame()

for ticker in tickers:
    if ticker == ticker_benchmark:
        continue
    active_return[ticker] = price_return[ticker] - price_return[ticker_benchmark]

active_return

,XLE,XLB,XLI,XLY,XLP,XLV,XLF,XLK,XLU,XLRE
Date,,,,,,,,,,
2017-01-31,-0.050014,0.027588,0.000759,0.024253,-0.000866,0.005034,-0.015304,0.017682,-0.005325,-0.019185
2017-02-28,-0.058049,-0.031617,0.001931,-0.019044,0.010530,0.026188,0.015569,0.008129,0.015466,0.009366
2017-03-31,-0.020345,0.003451,-0.011758,0.018683,-0.009048,-0.008012,-0.032618,0.018727,-0.008496,-0.016412
2017-04-28,-0.038562,0.003502,0.010583,0.014900,0.001902,0.006240,-0.017519,0.010980,-0.001490,-0.007509
2017-05-31,-0.046954,-0.011388,0.006211,-0.000584,0.014883,-0.003894,-0.023476,0.027960,0.029816,-0.004941
2017-06-30,-0.012760,0.008939,0.003924,-0.020410,-0.034828,0.036721,0.056261,-0.036832,-0.039732,0.005858
2017-07-31,0.006837,-0.003924,-0.016412,-0.000047,-0.012432,-0.011146,-0.002324,0.025242,0.004901,-0.007237
2017-08-31,-0.055335,0.007323,0.001649,-0.019154,-0.011573,0.016978,-0.016090,0.028670,0.032336,0.009579
2017-09-29,0.068199,0.012112,0.017799,-0.014619,-0.032646,-0.013890,0.027661,-0.014714,-0.054231,-0.039959
2017-10-31,-0.030512,0.016544,-0.014723,-0.000985,-0.038676,-0.029774,0.006427,0.042956,0.016832,-0.014124
2017-11-30,-0.010560,-0.018591,0.013578,0.022575,0.027672,0.001014,0.006504,-0.013944,-0.001232,0.001148
2017-12-29,0.035899,0.006454,0.005737,0.011275,0.005155,-0.019296,0.004340,-0.008109,-0.079090,-0.025078

### Calculate the tracking error and mean-adjusted tracking error for each SPDR in 2017

In [15]:
tracking_error = pd.DataFrame(index=["Tracking Error", "MATE"])

for ticker in tickers:
    if ticker == ticker_benchmark:
        continue
    tracking_error.loc["Tracking Error", ticker] = active_return[ticker].std()
    T = active_return[ticker].size
    tracking_error.loc["MATE", ticker] = np.sqrt(np.sum(active_return[ticker]**2)/T)

tracking_error

,XLE,XLB,XLI,XLY,XLP,XLV,XLF,XLK,XLU,XLRE
Tracking Error,0.038706,0.016058,0.010873,0.016878,0.020762,0.019164,0.024658,0.023002,0.033954,0.014863
MATE,0.041059,0.015468,0.010534,0.016220,0.020964,0.018356,0.023622,0.023751,0.033367,0.016859

### Identify the SPDR that best tracks the S&P 500 and explain how you came to this conclusion

### Answer: Accroding to the tracking error table, XLI best tracks the S&P500 because it has lowest MATE